let a = 7, b = 3;
console.log("====== Bai 3.1 =======");
console.log("a =",a);
console.log("b =",b);
console.log("Tổng a + b = ",a+b);
console.log("Hiệu a - b = ",a-b);
console.log("Tích a * b = ",a*b);
console.log("Thương a / b = ",a/b);
console.log("====== Bai 3.2 =======");
console.log("Trung bình cộng a và b là:",(a+b)/2);
console.log("====== Bai 3.3 =======");
let x = 3, y = 4, z = 6;
console.log("x =",x);
console.log("y =",y);
console.log("z =",z);
console.log("a. x^2 + 2x + 1 =",x**2 + 2*x + 1);
console.log("b. x^3 - 3xy - 5y + 3y^2 =",x**3 - 3*x*y - 5*y + 3*y**2);
console.log("c. (xy)^2 - 2x^2*y + 13y =", (x*y)**2 - 2*x**2*y + 13*y);
console.log("d. 4x^3 + 3xy + y^2 - (2x^2 - 3y) =",4*x**3 + 3*x*y + y**2 - (2*x**2 - 3*y));
console.log("e. (5x^2 / 4xy) + y^2 =",(5*x**2)/(4*x*y) + y**2);
console.log("f. x^2 - 2zxy / y^2 + 5x - 2y^2 + 4xz^3 + z^3 =",x**2 - (2*z*x*y)/(y**2) + 5*x -2*y**2 + 4*x*z**3 + z**3);